### PR TITLE
Created CONTRIBUTION.md file

### PR DESCRIPTION
**Pull request by dhrubo55**
Added contribution and pull request and code of conduct guidelines

### CODE REVIEW

**Comment by dhrubo55** [comment]
@RodrigoCMoraes  can you please review. Thank you

**Comment by RodrigoCMoraes** [comment]
Thanks @dhrubo55 !

**Comment by dhrubo55** [comment]
Most welcome. will you accept my PR and merge it?

**Comment by RodrigoCMoraes** [comment]
Sorry, I thought that I already have merged your PR, thanks for remember and sorry for delay.

**Comment by dhrubo55** [comment]
@RodrigoCMoraes its completely ok, and thank you.

**Pull request merged**
