### PR TITLE
Resolving issue1

### PR DESCRIPTION
**Pull request by mrunderline**
Resolving issue #1

### CODE REVIEW

**Comment by RodrigoCMoraes** [comment]
I tested in Windows 10 e it does not work, because in Windows for some reason we have to install Visual Studio, Cuda and others things manually to work properly. But with conda, all this packages are installed automatically and just inside on environment and it's awesome for reproducibility!!. I really would like to use _pipenv_ but at least for Windows it does not have all dependencies in PyPi so, can you test conda environment in you OS?

Steps to work with conda environment:

1. Install miniconda or conda (I use miniconda because just have the minimum packages to start to work)
2.  Copy content below to a file named **environment.yml**:
I
```
name: face_recognition
channels:
  - anaconda
  - defaults
dependencies:
  - tensorflow-gpu=1.14.0
  - pip:
    - keras==2.3.1
    - mtcnn==0.0.9
    - opencv-python==4.1.1.2
```

3. Create conda environment:

    ```conda env create -f environment.yml```

4. Activate conda environment:

    ```conda activate face_recognition```

5. Execute **mtcnn.py**:

    ```python mtcnn.py```

> Some warnings will appear but it's ok for now.

## After your tests
* If you like to delete conda environment:  ``` conda env remove -n face_recognition```
* If you like to unistall [mini]conda just remove miniconda directories like in this [link](https://docs.conda.io/projects/conda/en/latest/user-guide/install/linux.html#uninstalling-anaconda-or-miniconda).

**Comment by mrunderline** [comment]
@RodrigoCMoraes thanks for your help; I've done step by step as you said, and it's work fine.
now did you want to ignore the `pipenv` package manager and use `condo`?

**Comment by RodrigoCMoraes** [comment]
Thanks for testing @mrunderline , and I am glad that everything works fine.

Answering you question, yes, I would like to ignore `pipenv`, but I would like to ignore and `requeriments` files too. Maybe, can you delete then and update this PR?

**Comment by mrunderline** [comment]
Ops! something went wrong... I'll create a new PR

**Pull request closed without merging**
